"""
app.py
Smart PDF Form Filler — Streamlit UI
Supports: multiple applicants × multiple PDFs → ZIP download
"""

import json
import io
import streamlit as st
from pipeline import analyse_pdfs, fill_all_and_zip

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Smart PDF Form Filler",
    page_icon="📄",
    layout="wide",
)

# ── Styles ────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .main-header  { font-size: 2rem; font-weight: 700; color: #1e293b; }
    .sub-header   { font-size: 1rem; color: #64748b; margin-bottom: 1.5rem; }
    .step-label   { font-size: 0.78rem; font-weight: 700; text-transform: uppercase;
                    letter-spacing: 0.05em; color: #94a3b8; margin-bottom: 0.25rem; }
    .card         { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px;
                    padding: 16px 20px; margin-bottom: 1rem; }
    .badge        { display: inline-block; padding: 2px 10px; border-radius: 12px;
                    font-size: 0.75rem; font-weight: 600; }
    .badge-acroform { background: #dbeafe; color: #1d4ed8; }
    .badge-text     { background: #dcfce7; color: #15803d; }
    .badge-scanned  { background: #fef9c3; color: #a16207; }
    .missing-header { font-weight: 600; color: #b45309; margin-bottom: 0.5rem; }
    .log-box      { background: #0f172a; color: #94a3b8; border-radius: 8px;
                    padding: 12px 16px; font-size: 0.8rem; font-family: monospace;
                    max-height: 260px; overflow-y: auto; }
</style>
""", unsafe_allow_html=True)

# ── Header ────────────────────────────────────────────────────────────────────
st.markdown('<div class="main-header">📄 Smart PDF Form Filler</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="sub-header">Upload applicant data + PDF templates → '
    'AI fills every form for every applicant → download as ZIP</div>',
    unsafe_allow_html=True,
)

# ── Session state init ────────────────────────────────────────────────────────
for key in ["analysis", "applicants", "pdf_files", "log_lines", "analysis_done", "missing_overrides"]:
    if key not in st.session_state:
        st.session_state[key] = {} if key in ["analysis", "pdf_files", "missing_overrides"] else (
            [] if key in ["applicants", "log_lines"] else False
        )


def add_log(msg: str):
    st.session_state.log_lines.append(msg)


# ════════════════════════════════════════════════════════════════════════════════
# STEP 1 + 2: Uploads
# ════════════════════════════════════════════════════════════════════════════════
col1, col2 = st.columns(2, gap="large")

with col1:
    st.markdown('<div class="step-label">Step 1 — Applicant Data</div>', unsafe_allow_html=True)
    applicant_file = st.file_uploader(
        "Upload applicants.json (generated by generate_applicants.py)",
        type=["json"],
        key="applicant_upload",
    )
    if applicant_file:
        try:
            raw = json.loads(applicant_file.read())
            applicants = raw if isinstance(raw, list) else [raw]
            st.session_state.applicants = applicants
            st.success(f"✅ Loaded **{len(applicants)}** applicant(s)")
            with st.expander("Preview applicants"):
                for a in applicants:
                    st.markdown(f"- **{a.get('full_name', a.get('id'))}** — {a.get('city', '')}, {a.get('province_code', '')}")
        except Exception as e:
            st.error(f"Invalid JSON: {e}")

with col2:
    st.markdown('<div class="step-label">Step 2 — PDF Templates</div>', unsafe_allow_html=True)
    pdf_uploads = st.file_uploader(
        "Upload one or more PDF forms (T4, lease, insurance, etc.)",
        type=["pdf"],
        accept_multiple_files=True,
        key="pdf_upload",
    )
    if pdf_uploads:
        st.session_state.pdf_files = {f.name: f.read() for f in pdf_uploads}
        st.success(f"✅ Loaded **{len(pdf_uploads)}** PDF(s)")
        for f in pdf_uploads:
            st.markdown(f"- `{f.name}`")


# ════════════════════════════════════════════════════════════════════════════════
# STEP 3: Analyse
# ════════════════════════════════════════════════════════════════════════════════
st.divider()
st.markdown('<div class="step-label">Step 3 — Analyse PDFs</div>', unsafe_allow_html=True)

can_analyse = bool(st.session_state.applicants) and bool(st.session_state.pdf_files)
analyse_btn = st.button(
    "🔍 Analyse PDFs & Detect Missing Fields",
    type="primary",
    disabled=not can_analyse,
)

log_box = st.empty()

if analyse_btn:
    st.session_state.log_lines = []
    st.session_state.analysis_done = False
    st.session_state.analysis = {}
    st.session_state.missing_overrides = {}

    def refresh_log(msg):
        add_log(msg)
        log_box.markdown(
            '<div class="log-box">' + "<br>".join(st.session_state.log_lines) + "</div>",
            unsafe_allow_html=True,
        )

    with st.spinner("Analysing..."):
        try:
            analysis = analyse_pdfs(
                pdf_files=st.session_state.pdf_files,
                applicants=st.session_state.applicants,
                progress_callback=refresh_log,
            )
            st.session_state.analysis = analysis
            st.session_state.analysis_done = True
            refresh_log("✅ Analysis complete.")
        except Exception as e:
            refresh_log(f"❌ Analysis failed: {e}")
            import traceback
            st.code(traceback.format_exc())

# Persist log display after rerun
if st.session_state.log_lines:
    log_box.markdown(
        '<div class="log-box">' + "<br>".join(st.session_state.log_lines) + "</div>",
        unsafe_allow_html=True,
    )


# ════════════════════════════════════════════════════════════════════════════════
# STEP 4: Missing fields form
# ════════════════════════════════════════════════════════════════════════════════
if st.session_state.analysis_done:
    st.divider()
    st.markdown('<div class="step-label">Step 4 — Fill Missing Fields</div>', unsafe_allow_html=True)

    # Collect all unique missing fields across all PDFs
    all_missing: dict[str, str] = {}  # field_label → reason
    for pdf_name, entry in st.session_state.analysis.items():
        for mf in entry.get("missing_fields", []):
            label = mf.get("field_label", "")
            if label and label not in all_missing:
                all_missing[label] = mf.get("reason", "")

    if not all_missing:
        st.success("✅ No missing fields — all applicant data is complete. Ready to generate!")
    else:
        st.warning(
            f"⚠️ **{len(all_missing)} field(s)** could not be automatically filled. "
            "Provide values below (or leave blank to skip):"
        )

        with st.form("missing_fields_form"):
            overrides = {}
            cols = st.columns(2)
            for i, (label, reason) in enumerate(all_missing.items()):
                col = cols[i % 2]
                with col:
                    val = st.text_input(
                        label=label,
                        help=f"Why missing: {reason}",
                        key=f"missing_{label}",
                    )
                    overrides[label] = val

            submitted = st.form_submit_button("✅ Confirm & Proceed to Generate")
            if submitted:
                # Store only non-empty overrides
                st.session_state.missing_overrides = {k: v for k, v in overrides.items() if v.strip()}
                st.success("Values saved. Ready to generate!")


# ════════════════════════════════════════════════════════════════════════════════
# STEP 5: Generate ZIP
# ════════════════════════════════════════════════════════════════════════════════
if st.session_state.analysis_done:
    st.divider()
    st.markdown('<div class="step-label">Step 5 — Generate & Download</div>', unsafe_allow_html=True)

    # Show what will be generated
    n_applicants = len(st.session_state.applicants)
    n_pdfs = len(st.session_state.pdf_files)
    st.info(
        f"Will generate **{n_applicants * n_pdfs} filled PDF(s)** "
        f"({n_applicants} applicant(s) × {n_pdfs} template(s)), "
        "packaged as one ZIP with one folder per applicant."
    )

    # PDF type badges
    if st.session_state.analysis:
        badge_cols = st.columns(min(len(st.session_state.analysis), 4))
        for i, (pdf_name, entry) in enumerate(st.session_state.analysis.items()):
            pt = entry.get("type", "?")
            badge_cols[i % 4].markdown(
                f"`{pdf_name}` &nbsp; <span class='badge badge-{pt}'>{pt.upper()}</span>",
                unsafe_allow_html=True,
            )

    generate_btn = st.button("🚀 Generate All & Download ZIP", type="primary")

    if generate_btn:
        fill_log_lines = []
        fill_log_box = st.empty()

        def fill_log(msg):
            fill_log_lines.append(msg)
            fill_log_box.markdown(
                '<div class="log-box">' + "<br>".join(fill_log_lines) + "</div>",
                unsafe_allow_html=True,
            )

        with st.spinner("Filling all PDFs..."):
            try:
                zip_bytes = fill_all_and_zip(
                    pdf_files=st.session_state.pdf_files,
                    applicants=st.session_state.applicants,
                    analysis=st.session_state.analysis,
                    user_overrides=st.session_state.missing_overrides,
                    progress_callback=fill_log,
                )

                fill_log("✅ All PDFs generated successfully!")

                st.download_button(
                    label="⬇️ Download filled_forms.zip",
                    data=zip_bytes,
                    file_name="filled_forms.zip",
                    mime="application/zip",
                    use_container_width=True,
                )

                # Show ZIP contents tree
                import zipfile
                with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
                    names = sorted(zf.namelist())
                with st.expander("📦 ZIP contents"):
                    for name in names:
                        st.markdown(f"- `{name}`")

            except Exception as e:
                fill_log(f"❌ Generation failed: {e}")
                import traceback
                st.code(traceback.format_exc())
